### ISSUE TITLE
File github feature request to enable WSL2 on GHA

### ISSUE THREAD

**Issue by ssbarnea** [Vampire/setup-wsl#14]
Thanks for documenting the reasons why we do not have WSL2 support on GHA. Still, considering the both Microsoft and GitHub have a business interest in advertising both Windows and Github Actions, it would be in their interest to find a solution for enabling use of WSL2, one way or another.

It would be ideal to have this request also open so they can see the growing number of people asking for it so their product management can prioritize which features to implement first.

If I am correct the official public channel is https://github.community/c/code-to-cloud/github-actions/41 and it would worth mentioning `@ethomson` based on https://github.community/t/community-ama-lights-camera-actions/210397

**Comment by Vampire** [comment]
So you are asking me to ask them to add that feature? Why aren't you just asking them to add the feature yourself? For example at https://github.com/actions/virtual-environments/issues.

**Comment by ssbarnea** [comment]
I will do it. I was just pointing out that we need to start the process.

**Comment by Vampire** [comment]
If you opened an issue, you are welcome to post the link here, so that I can follow the outcome and if the possibility was added, I'm happy to add WSL2 support or accept a PR that adds it.
If it is ok for you, I'm closing this issue for now, as it is not really an issue with my action which just uses the possibilities that are given.

**Comment by Vampire** [comment]
For anyone following, version 4.0.0 will have support for WSLv2 (and theoretically any WSLvX) if nothing substantial changes.
