### ISSUE TITLE
WSLv1 or WSLv2: improve README in repo and in Marketplace

### ISSUE THREAD

**Issue by vadimkantorov** [Vampire/setup-wsl#2]
Is this action for setting up WSLv1 or WSLv2?

Thank you!

**Comment by Vampire** [comment]
The only possible, WSL 1.
I don't know whether Hyper-V is available and enabled, but either way, the current Windows build is 17763 and you need at least 18917 to be able to get WSL 2 running.

**Comment by vadimkantorov** [comment]
Oh, good for me actually, since WSLv1 is what I need :)

It would be nice if you specify this in README in the repo and in the Marketplace!

I also created an issue for improving README for `windows-2019` virtual environemnt: https://github.com/actions/virtual-environments/issues/2060

**Comment by vadimkantorov** [comment]
Very!

**Comment by Vampire** [comment]
Thanks
