### ISSUE TITLE
Add Ubuntu 22.04 distribution

### ISSUE THREAD

**Issue by kai2nenobu** [Vampire/setup-wsl#33]
We can download Ubuntu 22.04 WSL distribution from https://aka.ms/wslubuntu2204. This download link is recently added in a [document](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions).

I would be grateful if you could add `Ubuntu-22.04` to `setup-wsl`!

**Comment by Vampire** [comment]
I'll create a release today or tomorrow with the changes.
Work is done already.

**Comment by Vampire** [comment]
Release is out
