### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by stloeffler** [Vampire/setup-wsl#42]
When using the action, I get the following warning message:
```Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Vampire/setup-wsl```

**Comment by Vampire** [comment]
Thanks for notifying.
Should be gone now.
Please drop me a note if there are still issues.

**Comment by Vampire** [comment]
For anyone still following, I'm going to revert the Node.js upgrade with version 1.3.6, as it actually is a breaking change and thus needs to be done in a major version.
Older self-hosted runners or older GitHub Enterprise instances might not support Node.js 16 actions.
But I'll immediately thereafter create a v2 version that again increases the Node.js version to 16.
