### ISSUE TITLE
Introduce mobile tags

### ISSUE THREAD

**Issue by ssbarnea** [Vampire/setup-wsl#45]
To avoid forcing users to update on each release, you could use the [actions tagger](https://github.com/Actions-R-Us/actions-tagger) to update the mobile tags (or implement similar solution).

Examples of use of it https://github.com/coactions/dynamic-matrix/blob/main/.github/workflows/release.yml#L10-L14 -- if you check versions you will see how the short mobile tags are kept updated.

**Comment by Vampire** [comment]
> To avoid forcing users to update on each release

I don't, even without these horrible bad-practice moving tags.
I did it the proper way using branches.
My docs also show how you just use `v1` or `v2` to get the latest v1 or v2 version.

For a full explanation why this is majorly wrong, please see https://github.com/Vampire/setup-wsl/issues/44#issuecomment-1375288292

**Comment by Vampire** [comment]
Btw. I even documented it in the readme: https://github.com/Vampire/setup-wsl#version-numbers :-)
