### ISSUE TITLE
Warning: Node.js 16 actions are deprecated., please update to Node.js 20

### ISSUE THREAD

**Issue by joshuacwnewton** [Vampire/setup-wsl#52]
I get the following warning when using `setup-wsl@v2`:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Vampire/setup-wsl@v2
```

Please refer to: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

https://github.com/Vampire/setup-wsl/blob/b820055dadf3db715d00a242b31811d0abdf1ca3/action.yml#L110-L112

Related:

- https://github.com/Vampire/setup-wsl/issues/42

Thank you kindly for maintaining this action! :hearts:

**Comment by Vampire** [comment]
Thanks for notifying, it is updated and I will soon release v3 with the change.

**Comment by Vampire** [comment]
v3 landed

**Comment by joshuacwnewton** [comment]
Thank you so much! :hearts:
